add arm64 support
rancher/image-build-cni-plugins pull request #21
Opened 2023-05-06 21:23 UTC by briandowns

2023-05-07 00:32 UTC, brandond approved these changes

2023-05-08 08:47 UTC, rbrtbnfgl commented
Are you sure that it's building? If you change the building image version the `go-assert-boring.sh` script will fail for amd64. I fixed it there #20

2023-05-09 16:57 UTC, rbrtbnfgl approved these changes

2023-05-10 08:28 UTC, rbrtbnfgl commented on Dockerfile
> +RUN go-assert-static.sh bin/* && \
I think there is an issue with the build on this line.
If you check the drone build it prints an error.
```
#10 0.347 sh: missing ]
#10 0.347 /bin/sh: amd64: not found
```

2023-05-10 09:08 UTC, rbrtbnfgl commented on Dockerfile
> +    if [ "${ARCH}" != "s390x" || "${ARCH}" != "arm64" ]; then \
I think it should be an and here not or.

2023-05-10 09:15 UTC, rbrtbnfgl commented on Dockerfile
> +    if [ "${ARCH}" != "s390x" || "${ARCH}" != "arm64" ]; then \
```suggestion
    if [ "${ARCH}" != "s390x" ] && [ "${ARCH}" != "arm64" ]; then \
```

2023-05-10 09:20 UTC, rbrtbnfgl requested changes
With the changes on that if the build will fail at the `go-assert-boring.sh` that's why the `GOEPERIMENT` env is needed.

2023-05-10 18:21 UTC, rbrtbnfgl approved these changes

2023-05-11 16:46 UTC, brandond approved these changes

2023-05-23 21:10 UTC, merged